name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Dev Genesis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        go mod download
        go mod verify
    
    - name: Build
      working-directory: ./backend
      run: |
        make build
        ls -la ../dev-genesis
    
    - name: Test
      working-directory: ./backend
      run: go test -v ./...
    
    - name: Build for Windows
      working-directory: ./backend
      run: |
        make build-windows
        ls -la ../dev-genesis.exe
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dev-genesis-binaries
        path: |
          dev-genesis
          dev-genesis.exe
        retention-days: 7

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dev-genesis-binaries
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dev-genesis
          dev-genesis.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}